language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-28

    # Additional components
    - extra-android-m2repository

licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
before_script:
    - chmod +x gradlew

script: "./gradlew test"
