SELECT
     (SAMPLE(?location) as ?location)
     ?item
     ("mockLabel" as ?label)
     ("mockClass" as ?class)
     ("mockClassLabel" as ?classLabel)
     ("mockIcon" as ?icon)
     ?wikipediaArticle
     ?commonsArticle
     ("mockCategory" as ?commonsCategory)
     ("mockPic" as ?pic)
   WHERE {
     # Around given location...
     SERVICE wikibase:around {
       ?item wdt:P625 ?location.
       bd:serviceParam wikibase:center "Point(${LONG} ${LAT})"^^geo:wktLiteral.
       bd:serviceParam wikibase:radius "${RAD}" . # Radius in kilometers.
     }
   }
   GROUP BY ?item ?wikipediaArticle ?commonsArticle