SELECT
  ?item
  ?itemLabel
  ?itemDescription
  ?class
  ?classLabel
  ?pic
  ?destroyed
  ?endTime
  ?wikipediaArticle
  ?commonsArticle
  ?commonsCategory
  ?dateOfOfficialClosure
  ?pointInTime
WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    VALUES ?item {${ENTITY}}
  }

  # Get item label/class label/description in the preferred language of the user, or fallback.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "${LANG},${FALLBACK_LANGUAGES}".}

  # Get class (such as forest or bridge)
  OPTIONAL {?item p:P31/ps:P31 ?class}

  # Get picture (items without a picture will be shown in red on the Nearby map)
  OPTIONAL {?item wdt:P18 ?pic}

  # Get existence (whether an item still exists or not)
  OPTIONAL {?item wdt:P576 ?destroyed}
  OPTIONAL {?item wdt:P582 ?endTime}
  OPTIONAL {?item wdt:P3999 ?dateOfOfficialClosure}
  OPTIONAL {?item wdt:P585 ?pointInTime}

  # Get Commons category
  OPTIONAL {?item wdt:P373 ?commonsCategory}

  # Get Wikipedia article
  OPTIONAL {
    ?wikipediaArticle schema:about ?item.
    ?wikipediaArticle schema:isPartOf <https://en.wikipedia.org/>. # TODO internationalization
  }

  # Get Commons article
  OPTIONAL {
    ?commonsArticle schema:about ?item.
    ?commonsArticle schema:isPartOf <https://commons.wikimedia.org/>.
  }
}