SELECT
  ?item
  ?itemLabel
  ?itemDescription
  ?class
  ?classLabel
  ?pic
  ?destroyed
  ?endTime
  ?wikipediaArticle
  ?commonsArticle
  ?commonsCategory
  ?dateOfOfficialClosure
  ?pointInTime
WHERE {
  SERVICE <https://query.wikidata.org/sparql> {
    VALUES ?item { ${ENTITY} }
  }

  # Get item label/class label/description in the preferred language of the user
   SERVICE wikibase:label { bd:serviceParam wikibase:language "${LANG},en". }

  OPTIONAL { ?item p:P31/ps:P31 ?class. }

  # Get picture
  OPTIONAL {?item wdt:P18 ?pic}

  # Get existence
  OPTIONAL {?item wdt:P576 ?destroyed}
  OPTIONAL {?item wdt:P582 ?endTime}
  OPTIONAL {?item wdt:P3999 ?dateOfOfficialClosure}
  OPTIONAL {?item wdt:P585 ?pointInTime}

  # Get Commons category
  OPTIONAL {?item wdt:P373 ?commonsCategory}

  # Get Wikipedia article
  OPTIONAL { ?wikipediaArticle schema:about ?item;schema:isPartOf <https://en.wikipedia.org/>. }

  # Get Commons article
  OPTIONAL { ?commonsArticle schema:about ?item; schema:isPartOf <https://commons.wikimedia.org/>. }

}