SELECT
  ?item
  (SAMPLE(?location) as ?location)
WHERE {
  # Around given location.
  SERVICE wikibase:around {
    ?item wdt:P625 ?location.
    bd:serviceParam wikibase:center "Point(${LONG} ${LAT})"^^geo:wktLiteral.
    bd:serviceParam wikibase:radius "${RAD}" . # Radius in kilometers.
  }
}
GROUP BY ?item