SELECT
  ?item
  (SAMPLE(?location) as ?location)
WHERE {
  # Around given location
  SERVICE wikibase:box {
    ?item wdt:P625 ?location.
     bd:serviceParam wikibase:cornerWest "Point(${LONG_WEST} ${LAT_WEST})"^^geo:wktLiteral.
     bd:serviceParam wikibase:cornerEast "Point(${LONG_EAST} ${LAT_EAST})"^^geo:wktLiteral.
  }

}
GROUP BY ?item